# Generated by Django 4.2.18 on 2025-01-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_relationship_tag_relationship_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
